'use strict';var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,d){a!=Array.prototype&&a!=Object.prototype&&(a[e]=d.value)};
$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var e=0;e<a.length;++e){var d=a[e];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,d,m){if(e){d=$jscomp.global;a=a.split(".");for(m=0;m<a.length-1;m++){var n=a[m];n in d||(d[n]={});d=d[n]}a=a[a.length-1];m=d[a];e=e(m);e!=m&&null!=e&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6","es3");
$jscomp.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6","es3");
(function(a){"object"==typeof exports&&"object"==typeof module?a(require("codemirror/lib/codemirror")):"function"==typeof define&&define.amd?define(["codemirror/lib/codemirror"],a):a(CodeMirror)})(function(a){function e(a){var c=a.state.sfdc;a.clearGutter("CodeMirror-sfdc-markers");if(c.marked&&0<c.marked.length){for(a=0;a<c.marked.length;++a)c.marked[a].clear();c.marked.length=0}}function d(a){var c=a.severity;c||(c="error");var g=document.createElement("div");g.className="CodeMirror-sfdc-message-"+
c;"undefined"!=typeof a.messageHTML?g.innerHTML=a.messageHTML:g.appendChild(document.createTextNode(a.message));return g}function m(c,e,g,d,b){var f=document.createElement("div"),h=f;f.className="CodeMirror-sfdc-marker-"+g;d&&(h=f.appendChild(document.createElement("div")),h.className="CodeMirror-sfdc-marker-multiple");if(0!=b)a.on(h,"mouseover",function(a){q(c,a,e,h)});return f}function n(c,e,g){function d(c){if(!b.parentNode)return a.off(document,"mousemove",d);b.style.top=Math.max(0,c.clientY-
b.offsetHeight-5)+"px";b.style.left=c.clientX+5+"px"}var b=document.createElement("div");b.className="CodeMirror-sfdc-tooltip cm-s-"+c.options.theme;b.appendChild(g.cloneNode(!0));document.body.appendChild(b);d(e);null!=b.style.opacity&&(b.style.opacity=1);return b}function r(a){a.parentNode&&(null==a.style.opacity&&a.parentNode&&a.parentNode.removeChild(a),a.style.opacity=0,setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},600))}function q(c,e,d,k){function b(){a.off(k,"mouseout",
b);f&&(r(f),f=null)}var f=n(c,e,d);a.on(k,"mouseout",b)}a.defineExtension("clearSfdcMarkers",function(){e(this)});a.defineExtension("showSfdcMarkers",function(c){e(this);for(var n=this.state.sfdc,g=[],k=0;k<c.length;k++){var b=c[k];if(b&&Number.isInteger(b.line)&&!(0>=b.line)){if(Number.isInteger(b.character)&&1<=b.character){var f=b.character-1;var h=f+1;b.evidence&&0<b.evidence.length&&(h=f+b.evidence.length);f=a.Pos(b.line-1,f);h=a.Pos(b.line-1,h)}else f=a.Pos(b.line-1),h=a.Pos(b.line-1);var l=
b.line-1;(g[l]||(g[l]=[])).push({line:l,message:b.message,severity:b.severity,from:f,to:h})}}for(c=0;c<g.length;++c)if(k=g[c]){b=null;f=document.createDocumentFragment();for(h=0;h<k.length;++h){l=k[h];var p=l.severity;p||(p="error");b&&"error"===b||(b=p);f.appendChild(d(l));l.to&&n.marked.push(this.markText(l.from,l.to,{className:"CodeMirror-sfdc-marktext-"+p,__annotation:l}))}this.setGutterMarker(c,"CodeMirror-sfdc-markers",m(this,f,b,1<k.length,!0))}});a.defineOption("sfdc",!1,function(c,d,g){g&&
g!=a.Init&&(e(),delete c.state.sfdc);d&&(c.state.sfdc={marked:[]})})});
